################################################################################
################################################################################
###
###  This file is automatically generated. Do not change this file! Changes
###  will get overwritten! Change the source file for "setup.py" instead.
###  This is either 'packageinfo.json' or 'packageinfo.jsonc'
###
################################################################################
################################################################################


from setuptools import setup

def readme():
	with open("README.md", "r", encoding="UTF-8-sig") as f:
		return f.read()

setup(
	author = "Jürgen Knauth",
	author_email = "pubsrc@binary-overflow.de",
	classifiers = [
		"Development Status :: 4 - Beta",
		"License :: OSI Approved :: Apache Software License",
		"Programming Language :: Python :: 3",
	],
	description = "This Python module implements a set of classes for easy, programmatic generation of SVG graphics.",
	include_package_data = False,
	install_requires = [
	],
	keywords = [
		"svg",
	],
	license = "Apache2",
	name = "jk_svg",
	packages = [
		"jk_svg",
	],
	version = "0.2021.1.2",
	zip_safe = False,
	long_description = readme(),
	long_description_content_type="text/markdown",
)
